### ISSUE TITLE
gui: support multiple use cases

### ISSUE THREAD

**Issue by obfusk** [obfusk/kanjidraw#10]
- [x] print to stdout instead of copying to clipboard (for scripting)?
- [x] "oneshot" mode to draw one character, copy/print it, and exit?
- [x] "multiple" mode to draw multiple characters and copy/print all of them when done?

**Comment by obfusk** [comment]
@maxigaz ideas are welcome :)

**Comment by maxigaz** [comment]
Thank you for working on this. Having kanjidraw as a lightweight standalone tool on the desktop is already nice, although here's how I think it could be improved further:

- Apply a slight blur on the lines of the drawing. I noticed that the version embedded into Jiten has this, but the standalone version produces sharp edges, which doesn't look as good IMO.
- Tweak the UI colours, for example by reducing the contrast for the background/foreground. You could go further and use Qt or GTK+ so that it follows the system theme, although that might somewhat increase the complexity and the loading time, so I leave this one up to you to decide.
- Add a close button. Below you can see how it looks for me, when I open it in i3 by default. Apart from the huge area filled with black (which goes back to my previous point), you may notice that I don't have a title bar, so I don't have clickable buttons for closing, minimizing etc.

![kanjidraw-standalone](https://user-images.githubusercontent.com/10419911/118724092-7a9c4480-b82e-11eb-9754-e032c59d6529.png)

P.S.: I've just noticed that the tick inside the checkbox is also barely visible.

Apart from that, I like the ideas you mentioned, especially the second and forth ones.

**Comment by obfusk** [comment]
> Apply a slight blur on the lines of the drawing. I noticed that the version embedded into Jiten has this, but the standalone version produces sharp edges, which doesn't look as good IMO.

Good idea. But that's a difference between an HTML5 canvas and a Tk canvas that I don't think I can fix.

> Tweak the UI colours, for example by reducing the contrast for the background/foreground. You could go further and use Qt or GTK+ so that it follows the system theme, although that might somewhat increase the complexity and the loading time, so I leave this one up to you to decide.

I might port it to Qt/GTK at some point. But that's not trivial and adds an extra dependency. I used Tk so that it should easily work on other operating systems as well (since it's part of the Python standard library).

But if you want, I can probably add options to set the colours.

> Add a close button. Below you can see how it looks for me, when I open it in i3 by default. Apart from the huge area filled with black (which goes back to my previous point), you may notice that I don't have a title bar, so I don't have clickable buttons for closing, minimizing etc. (This isn't a huge deal, by the way, because I already have some other ways to work around that, I'm just mentioning this as something "nice to have".)

I would assume i3 users don't need a "close" button though ;)
FWIW you can now simply press `q` to quit.

> P.S.: I've just noticed that the tick inside the checkbox is also barely visible.

I use i3 as well. The checkbuttons look fine here and I've told i3 to automatically make it a floating window.

This is how it looks for me:

![Screenshot from 2021-05-19 01-42-44](https://user-images.githubusercontent.com/1260687/118737041-4b90cd80-b844-11eb-8d52-0e3d5a145262.png)

> Apart from that, I like the ideas you mentioned, especially the second and forth ones.

I've implemented most of them (on `master`, not part of a release yet).

For some (i3) examples, see https://github.com/obfusk/kanjidraw#examples

**Comment by maxigaz** [comment]
> FWIW you can now simply press `q` to quit.

Pressing `q` or `Ctrl-q` doesn't do anything for me (in v0.2.1.).

> This is how it looks for me:

You're using a light colour theme system-wise, aren't you? I use arc-dark, and from time to time I come across applications that only partially follow this theme, which results in the background being way too bright at some places or some text being illegible (like the tick in the checkbox). Maybe using a dark theme messes with Tk in some way, too?

> For some (i3) examples, see https://github.com/obfusk/kanjidraw#examples

Making it float automatically through a rule has crossed my mind, but haven't actually written it. I'll give it a try, thank you!

**Comment by obfusk** [comment]
> Pressing `q` or `Ctrl-q` doesn't do anything for me (in v0.2.1.). (Edit: Or did you mean the master branch? I think I'll wait for a new release for now.)

Yes, it was only on `master`. But I've just released `v0.2.2`.

> You're using a light colour theme system-wise, aren't you? I use arc-dark, and from time to time I come across applications that only partially follow this theme, which results in the background being way too bright at some places or some text being illegible (like the tick in the checkbox). Maybe using a dark theme messes with Tk in some way, too?

Yes, I'm using a light colour theme. And yes, your dark theme seems to affect Tk. Not much I can do about that.

I've now added custom dark/light themes directly to `kanjidraw` (you'll need to use either `--dark` or export `KANJIDRAW_DARK=1`).
Please test it and let me know if it works for you.

> Making it float automatically through a rule has crossed my mind, but haven't actually written it. I'll give it a try, thank you!

No problem. I was already using that myself anyway :)

**Comment by obfusk** [comment]
> Yes, I'm using a light colour theme.

Ironically, I usually have dozens of terminal "tabs" open, all white on black.
But dark themes almost never work for me (I think `NewPipe` is one of the few exceptions).

**Comment by maxigaz** [comment]
I've just tried v0.2.2. `--dark` works and the new colourscheme looks more appealing. The keyboard bindings also work.

Thank you!

**Comment by obfusk** [comment]
> I've just tried v0.2.2. `--dark` works and the new colourscheme looks more appealing.

Would you mind uploading a screenshot (both light and dark) so I can see whether it looks the same with your different default theme?

> The keyboard bindings also work.

Do you mean in `kanjidraw`, i3, or both?

**Comment by maxigaz** [comment]
> Would you mind uploading a screenshot (both light and dark) so I can see whether it looks the same with your different default theme?

![kanjidraw-light](https://user-images.githubusercontent.com/10419911/118876894-117c0600-b8ee-11eb-8fbf-8da4c6284d19.png)
![kanjidraw-light2](https://user-images.githubusercontent.com/10419911/118876903-13de6000-b8ee-11eb-892e-e7446957efa5.png)
![kanjidraw-dark](https://user-images.githubusercontent.com/10419911/118876836-fd380900-b8ed-11eb-803e-5d2ccc4dc870.png)
![kanjidraw-dark2](https://user-images.githubusercontent.com/10419911/118876846-0032f980-b8ee-11eb-8a77-c24e9f42b650.png)

> > The keyboard bindings also work.
> 
> Do you mean in `kanjidraw`, i3, or both?

I meant `q`, `Ctrl-q`, and `Esc`.

**Comment by obfusk** [comment]
Thanks! The colours look the same... but the button shapes don't.

I just released `v0.2.3`, could you confirm that makes it look like this (i.e. square buttons, no change in window size after clicking "done") for you too?

![Screenshot from 2021-05-19 23-37-41](https://user-images.githubusercontent.com/1260687/118888025-696d3980-b8fb-11eb-864a-10ea60a71237.png)

**Comment by maxigaz** [comment]
> Thanks! The colours look the same... but the button shapes don't.
> 
> I just released `v0.2.3`, could you confirm that makes it look like this (i.e. square buttons, no change in window size after clicking "done") for you too?

Yes, they have a square shape now, even if I manually resize the window.

![kanjidraw-buttons](https://user-images.githubusercontent.com/10419911/118889795-ebf6f880-b8fd-11eb-9bcb-aac9648d52db.png)

Speaking of resizing, the window doesn't have a minimum size limit, so I can shrink it until it looks like this:

![kanjidraw-buttons2](https://user-images.githubusercontent.com/10419911/118889797-ec8f8f00-b8fd-11eb-96c8-dd67310b9822.png)

**Comment by obfusk** [comment]
> Speaking of resizing, the window doesn't have a minimum size limit, so I can shrink it until it looks like this

I know. Tk is a bit weird sometimes. I made the window size fixed on `master` (not that i3 cares unless it's floating).

**Comment by obfusk** [comment]
> Yes, they have a square shape now, even if I manually resize the window.

Thanks for checking.
